### PR TITLE
Add OpenCL support

### LINKED ISSUE #44: OpenCL support
I tried implementing OpenCL support and the code is at: https://github.com/napsternxg/neural-style/tree/opencl

However I get the following error when running the code:

```
$ $ th neural_style_opencl.lua -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -gpu 0 -backend 'clnn' -output_image profile.png
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Using Advanced Micro Devices, Inc. , OpenCL platform: AMD Accelerated Parallel Processing
Using OpenCL device: Turks
/home/torch/install/bin/luajit: C++ exception
```

I believe the issue is because of the SpatialConvolutionMM which is implemented in ccn2 module.

### PR DESCRIPTION
**Pull request by napsternxg**
Add OpenCL support with help from @hughperkins and @jcjohnson. 
Add example for using NIN Imagenet model
Update README with example for running using OpenCL and NIN. 

Closes #44

### CODE REVIEW

**Comment by hughperkins** [comment]
Hi Shubhanshu, looks good. Dont suppose... do you have an example output photo that looks a bit more Picasso-like :-)  (If you dont, I think I have a few lieing around, or else you could grab one of the photos on the original OpenCL issue thread perhaps?)

**Comment by napsternxg** [comment]
@hughperkins yeah these are the images I generated using the NIN model and the new OpenCL code. 

profile
profile_700
profile_picasso

**Comment by hughperkins** [comment]
Yes.  I think it'd be good to have some images comparable with the CUDA ones.  Otherwise it looks like the opencl version just kind of produces blurry copies of the original photo, with the colors changed a bit :-P  Can you maybe add some of the photos from the OpenCL thread perhaps?

**Comment by jcjohnson** [comment]
Huge thanks to @hughperkins and @napsternxg for getting this to work! I'm traveling for the next couple weeks so I may be a bit slow to test and merge.

**Comment by jcjohnson** [comment]
Actually merging wasn't too bad at all, but I had to work around the removal of loadcaffe_wrapper.

In the case of `clnn` backend, I'm using `loadcaffe

**Comment by jcjohnson** [comment]
It turns out that merging wasn't too bad. I did have to work around the removal of the loadcaffe_wrapper though.

In the case of a `clnn` backend, I'm using `loadcaffe` to load with `nn` backend, then casting the whole thing to `clnn`. Running the same image with `cudnn` and `clnn` seems to give the same results:

This one is using `cudnn`:
out_cudnn

This one is using the same settings with `clnn`:
out_clnn

**Comment by hughperkins** [comment]
Awesome!  Thank you Justin.  And thank you for having taken the time to check that the results are comparable, and providing the outputs from this.  Not sure they are quite exactly the same, but seem fairly similar :-)

**Comment by napsternxg** [comment]
Thanks guys for all the help =) This completes my first pull request to a torch library =)

**Comment by hughperkins** [comment]
Thank you Shubhanshu :-)

**Pull request merged**
